// Code generated by "go generate"; DO NOT EDIT.

package network

import (
	"context"
	"iter"

	"github.com/viettelcloud-oss/sdks/go/core"
)

// ListElasticIps List Elastic Ips
//
// GET /v2/network/elastic-ips/
func (c *Client) ListElasticIps(ctx context.Context, params ListElasticIpsParams) (*PagedElasticIPSchema, error) {
	genParams := params
	resp, err := c.gen.ListElasticIpsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateElasticIp Create Elastic Ip
//
// POST /v2/network/elastic-ips/
func (c *Client) CreateElasticIp(ctx context.Context, params CreateElasticIpParams, body ElasticIPCreateSchema) (*ElasticIPSchema, error) {
	genParams := params
	resp, err := c.gen.CreateElasticIpWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetElasticIp Get Elastic Ip
//
// GET /v2/network/elastic-ips/{eip_id}/
func (c *Client) GetElasticIp(ctx context.Context, EipID core.UUID, params GetElasticIpParams) (*ElasticIPDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetElasticIpWithResponse(ctx, EipID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateElasticIp Update Elastic Ip
//
// PUT /v2/network/elastic-ips/{eip_id}/
func (c *Client) UpdateElasticIp(ctx context.Context, EipID core.UUID, params UpdateElasticIpParams, body ElasticIPUpdateSchema) (*ElasticIPDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateElasticIpWithResponse(ctx, EipID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateElasticIp Partial Update Elastic Ip
//
// PATCH /v2/network/elastic-ips/{eip_id}/
func (c *Client) PartialUpdateElasticIp(ctx context.Context, EipID core.UUID, params PartialUpdateElasticIpParams, body ElasticIPPartialUpdateSchema) (*ElasticIPDetailSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateElasticIpWithResponse(ctx, EipID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteElasticIp Delete Elastic Ip
//
// DELETE /v2/network/elastic-ips/{eip_id}/
func (c *Client) DeleteElasticIp(ctx context.Context, EipID core.UUID, params DeleteElasticIpParams) error {
	genParams := params
	resp, err := c.gen.DeleteElasticIpWithResponse(ctx, EipID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// EstimateElasticIpCost Estimate Elastic Ip Cost
//
// POST /v2/network/elastic-ips/estimate-cost/
func (c *Client) EstimateElasticIpCost(ctx context.Context, params EstimateElasticIpCostParams, body ElasticIPCreateSchema) (*EstimatedPaygCostSchema, error) {
	genParams := params
	resp, err := c.gen.EstimateElasticIpCostWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListVpcs List Vpcs
//
// GET /v2/network/vpcs/
func (c *Client) ListVpcs(ctx context.Context, params ListVpcsParams) (*PagedVPCSchema, error) {
	genParams := params
	resp, err := c.gen.ListVpcsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateVpc Create Vpc
//
// POST /v2/network/vpcs/
func (c *Client) CreateVpc(ctx context.Context, params CreateVpcParams, body VPCCreateSchema) (*VPCSchema, error) {
	genParams := params
	resp, err := c.gen.CreateVpcWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetVpc Get Vpc
//
// GET /v2/network/vpcs/{vpc_id}/
func (c *Client) GetVpc(ctx context.Context, VPCID core.UUID, params GetVpcParams) (*VPCSchema, error) {
	genParams := params
	resp, err := c.gen.GetVpcWithResponse(ctx, VPCID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateVpc Update Vpc
//
// PUT /v2/network/vpcs/{vpc_id}/
func (c *Client) UpdateVpc(ctx context.Context, VPCID core.UUID, params UpdateVpcParams, body VPCUpdateSchema) (*VPCSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateVpcWithResponse(ctx, VPCID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteVpc Delete Vpc
//
// DELETE /v2/network/vpcs/{vpc_id}/
func (c *Client) DeleteVpc(ctx context.Context, VPCID core.UUID, params DeleteVpcParams) error {
	genParams := params
	resp, err := c.gen.DeleteVpcWithResponse(ctx, VPCID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ShareVpc Share Vpc
//
// POST /v2/network/vpcs/{vpc_id}/share/
func (c *Client) ShareVpc(ctx context.Context, VPCID core.UUID, params ShareVpcParams, body VPCShareSchema) (*VPCSchema, error) {
	genParams := params
	resp, err := c.gen.ShareVpcWithResponse(ctx, VPCID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UnshareVpc Unshare Vpc
//
// POST /v2/network/vpcs/{vpc_id}/unshare/
func (c *Client) UnshareVpc(ctx context.Context, VPCID core.UUID, params UnshareVpcParams, body VPCUnshareSchema) (*VPCSchema, error) {
	genParams := params
	resp, err := c.gen.UnshareVpcWithResponse(ctx, VPCID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListSubnets List Subnets
//
// GET /v2/network/subnets/
func (c *Client) ListSubnets(ctx context.Context, params ListSubnetsParams) (*PagedSubnetSchema, error) {
	genParams := params
	resp, err := c.gen.ListSubnetsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateSubnet Create Subnet
//
// POST /v2/network/subnets/
func (c *Client) CreateSubnet(ctx context.Context, params CreateSubnetParams, body SubnetCreateSchema) (*SubnetSchema, error) {
	genParams := params
	resp, err := c.gen.CreateSubnetWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetSubnet Get Subnet
//
// GET /v2/network/subnets/{subnet_id}/
func (c *Client) GetSubnet(ctx context.Context, SubnetID core.UUID, params GetSubnetParams) (*SubnetSchema, error) {
	genParams := params
	resp, err := c.gen.GetSubnetWithResponse(ctx, SubnetID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateSubnet Update Subnet
//
// PUT /v2/network/subnets/{subnet_id}/
func (c *Client) UpdateSubnet(ctx context.Context, SubnetID core.UUID, params UpdateSubnetParams, body SubnetUpdateSchema) (*SubnetSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateSubnetWithResponse(ctx, SubnetID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateSubnet Partial Update Subnet
//
// PATCH /v2/network/subnets/{subnet_id}/
func (c *Client) PartialUpdateSubnet(ctx context.Context, SubnetID core.UUID, params PartialUpdateSubnetParams, body SubnetPartialUpdateSchema) (*SubnetSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateSubnetWithResponse(ctx, SubnetID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteSubnet Delete Subnet
//
// DELETE /v2/network/subnets/{subnet_id}/
func (c *Client) DeleteSubnet(ctx context.Context, SubnetID core.UUID, params DeleteSubnetParams) error {
	genParams := params
	resp, err := c.gen.DeleteSubnetWithResponse(ctx, SubnetID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListPrivateIps List Private Ips
//
// GET /v2/network/private-ips/
func (c *Client) ListPrivateIps(ctx context.Context, params ListPrivateIpsParams) (*PagedPrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.ListPrivateIpsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreatePrivateIp Create Private Ip
//
// POST /v2/network/private-ips/
func (c *Client) CreatePrivateIp(ctx context.Context, params CreatePrivateIpParams, body PrivateIPCreateSchema) (*PrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.CreatePrivateIpWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetPrivateIp Get Private Ip
//
// GET /v2/network/private-ips/{private_ip_id}/
func (c *Client) GetPrivateIp(ctx context.Context, PrivateIPID core.UUID, params GetPrivateIpParams) (*PrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.GetPrivateIpWithResponse(ctx, PrivateIPID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdatePrivateIp Update Private Ip
//
// PUT /v2/network/private-ips/{private_ip_id}/
func (c *Client) UpdatePrivateIp(ctx context.Context, PrivateIPID core.UUID, params UpdatePrivateIpParams, body PrivateIPUpdateSchema) (*PrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.UpdatePrivateIpWithResponse(ctx, PrivateIPID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdatePrivateIp Partial Update Private Ip
//
// PATCH /v2/network/private-ips/{private_ip_id}/
func (c *Client) PartialUpdatePrivateIp(ctx context.Context, PrivateIPID core.UUID, params PartialUpdatePrivateIpParams, body PrivateIPPartialUpdateSchema) (*PrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdatePrivateIpWithResponse(ctx, PrivateIPID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeletePrivateIp Delete Private Ip
//
// DELETE /v2/network/private-ips/{private_ip_id}/
func (c *Client) DeletePrivateIp(ctx context.Context, PrivateIPID core.UUID, params DeletePrivateIpParams) error {
	genParams := params
	resp, err := c.gen.DeletePrivateIpWithResponse(ctx, PrivateIPID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// UpdatePrivateIpAllowedVips Update Private Ip Allowed Vips
//
// PUT /v2/network/private-ips/{private_ip_id}/allowed-vips/
func (c *Client) UpdatePrivateIpAllowedVips(ctx context.Context, PrivateIPID core.UUID, params UpdatePrivateIpAllowedVipsParams, body PrivateIPAllowedVIPsUpdateSchema) (*PrivateIPSchema, error) {
	genParams := params
	resp, err := c.gen.UpdatePrivateIpAllowedVipsWithResponse(ctx, PrivateIPID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListSecurityGroups List Security Groups
//
// GET /v2/network/security-groups/
func (c *Client) ListSecurityGroups(ctx context.Context, params ListSecurityGroupsParams) (*PagedSecurityGroupSchema, error) {
	genParams := params
	resp, err := c.gen.ListSecurityGroupsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateSecurityGroup Create Security Group
//
// POST /v2/network/security-groups/
func (c *Client) CreateSecurityGroup(ctx context.Context, params CreateSecurityGroupParams, body SecurityGroupCreateSchema) (*SecurityGroupSchema, error) {
	genParams := params
	resp, err := c.gen.CreateSecurityGroupWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetSecurityGroup Get Security Group
//
// GET /v2/network/security-groups/{security_group_id}/
func (c *Client) GetSecurityGroup(ctx context.Context, SecurityGroupID core.UUID, params GetSecurityGroupParams) (*SecurityGroupSchema, error) {
	genParams := params
	resp, err := c.gen.GetSecurityGroupWithResponse(ctx, SecurityGroupID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateSecurityGroup Update Security Group
//
// PUT /v2/network/security-groups/{security_group_id}/
func (c *Client) UpdateSecurityGroup(ctx context.Context, SecurityGroupID core.UUID, params UpdateSecurityGroupParams, body SecurityGroupUpdateSchema) (*SecurityGroupSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateSecurityGroupWithResponse(ctx, SecurityGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateSecurityGroup Partial Update Security Group
//
// PATCH /v2/network/security-groups/{security_group_id}/
func (c *Client) PartialUpdateSecurityGroup(ctx context.Context, SecurityGroupID core.UUID, params PartialUpdateSecurityGroupParams, body SecurityGroupPartialUpdateSchema) (*SecurityGroupSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateSecurityGroupWithResponse(ctx, SecurityGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteSecurityGroup Delete Security Group
//
// DELETE /v2/network/security-groups/{security_group_id}/
func (c *Client) DeleteSecurityGroup(ctx context.Context, SecurityGroupID core.UUID, params DeleteSecurityGroupParams) error {
	genParams := params
	resp, err := c.gen.DeleteSecurityGroupWithResponse(ctx, SecurityGroupID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListSecurityGroupRules List Security Group Rules
//
// GET /v2/network/security-group-rules/
func (c *Client) ListSecurityGroupRules(ctx context.Context, params ListSecurityGroupRulesParams) (*PagedSecurityGroupRuleSchema, error) {
	genParams := params
	resp, err := c.gen.ListSecurityGroupRulesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateSecurityGroupRule Create Security Group Rule
//
// POST /v2/network/security-group-rules/
func (c *Client) CreateSecurityGroupRule(ctx context.Context, params CreateSecurityGroupRuleParams, body SecurityGroupRuleCreateSchema) (*SecurityGroupRuleSchema, error) {
	genParams := params
	resp, err := c.gen.CreateSecurityGroupRuleWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetSecurityGroupRule Get Security Group Rule
//
// GET /v2/network/security-group-rules/{security_group_rule_id}/
func (c *Client) GetSecurityGroupRule(ctx context.Context, SecurityGroupRuleID core.UUID, params GetSecurityGroupRuleParams) (*SecurityGroupRuleSchema, error) {
	genParams := params
	resp, err := c.gen.GetSecurityGroupRuleWithResponse(ctx, SecurityGroupRuleID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateSecurityGroupRule Update Security Group Rule
//
// PUT /v2/network/security-group-rules/{security_group_rule_id}/
func (c *Client) UpdateSecurityGroupRule(ctx context.Context, SecurityGroupRuleID core.UUID, params UpdateSecurityGroupRuleParams, body SecurityGroupRuleUpdateSchema) (*SecurityGroupRuleSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateSecurityGroupRuleWithResponse(ctx, SecurityGroupRuleID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateSecurityGroupRule Partial Update Security Group Rule
//
// PATCH /v2/network/security-group-rules/{security_group_rule_id}/
func (c *Client) PartialUpdateSecurityGroupRule(ctx context.Context, SecurityGroupRuleID core.UUID, params PartialUpdateSecurityGroupRuleParams, body SecurityGroupRulePartialUpdateSchema) (*SecurityGroupRuleSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateSecurityGroupRuleWithResponse(ctx, SecurityGroupRuleID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteSecurityGroupRule Delete Security Group Rule
//
// DELETE /v2/network/security-group-rules/{security_group_rule_id}/
func (c *Client) DeleteSecurityGroupRule(ctx context.Context, SecurityGroupRuleID core.UUID, params DeleteSecurityGroupRuleParams) error {
	genParams := params
	resp, err := c.gen.DeleteSecurityGroupRuleWithResponse(ctx, SecurityGroupRuleID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListElasticIpsIter returns an iterator over all ElasticIPSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListElasticIpsIter(ctx context.Context, params ListElasticIpsParams) iter.Seq2[*ElasticIPSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ElasticIPSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListElasticIps(ctx, p)
		if err != nil {
			return core.Page[ElasticIPSchema]{}, err
		}
		return core.Page[ElasticIPSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListVpcsIter returns an iterator over all VPCSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListVpcsIter(ctx context.Context, params ListVpcsParams) iter.Seq2[*VPCSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[VPCSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListVpcs(ctx, p)
		if err != nil {
			return core.Page[VPCSchema]{}, err
		}
		return core.Page[VPCSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListSubnetsIter returns an iterator over all SubnetSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListSubnetsIter(ctx context.Context, params ListSubnetsParams) iter.Seq2[*SubnetSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[SubnetSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListSubnets(ctx, p)
		if err != nil {
			return core.Page[SubnetSchema]{}, err
		}
		return core.Page[SubnetSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListPrivateIpsIter returns an iterator over all PrivateIPSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListPrivateIpsIter(ctx context.Context, params ListPrivateIpsParams) iter.Seq2[*PrivateIPSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[PrivateIPSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListPrivateIps(ctx, p)
		if err != nil {
			return core.Page[PrivateIPSchema]{}, err
		}
		return core.Page[PrivateIPSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListSecurityGroupsIter returns an iterator over all SecurityGroupSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListSecurityGroupsIter(ctx context.Context, params ListSecurityGroupsParams) iter.Seq2[*SecurityGroupSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[SecurityGroupSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListSecurityGroups(ctx, p)
		if err != nil {
			return core.Page[SecurityGroupSchema]{}, err
		}
		return core.Page[SecurityGroupSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListSecurityGroupRulesIter returns an iterator over all SecurityGroupRuleSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListSecurityGroupRulesIter(ctx context.Context, params ListSecurityGroupRulesParams) iter.Seq2[*SecurityGroupRuleSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[SecurityGroupRuleSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListSecurityGroupRules(ctx, p)
		if err != nil {
			return core.Page[SecurityGroupRuleSchema]{}, err
		}
		return core.Page[SecurityGroupRuleSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}
