// Code generated by "go generate"; DO NOT EDIT.

package loadbalancer

import (
	"context"
	"iter"

	"github.com/viettelcloud-oss/sdks/go/core"
)

// ListLoadBalancers List Load Balancers
//
// GET /v2/load-balancing/loadbalancers/
func (c *Client) ListLoadBalancers(ctx context.Context, params ListLoadBalancersParams) (*PagedLoadBalancerSchema, error) {
	genParams := params
	resp, err := c.gen.ListLoadBalancersWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateLoadBalancer Create Load Balancer
//
// POST /v2/load-balancing/loadbalancers/
func (c *Client) CreateLoadBalancer(ctx context.Context, params CreateLoadBalancerParams, body LoadBalancerCreateSchema) (*LoadBalancerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.CreateLoadBalancerWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetLoadBalancer Get Load Balancer
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/
func (c *Client) GetLoadBalancer(ctx context.Context, LoadBalancerID core.UUID, params GetLoadBalancerParams) (*LoadBalancerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetLoadBalancerWithResponse(ctx, LoadBalancerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateLoadBalancer Update Load Balancer
//
// PUT /v2/load-balancing/loadbalancers/{load_balancer_id}/
func (c *Client) UpdateLoadBalancer(ctx context.Context, LoadBalancerID core.UUID, params UpdateLoadBalancerParams, body LoadBalancerUpdateSchema) (*LoadBalancerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateLoadBalancerWithResponse(ctx, LoadBalancerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateLoadBalancer Partial Update Load Balancer
//
// PATCH /v2/load-balancing/loadbalancers/{load_balancer_id}/
func (c *Client) PartialUpdateLoadBalancer(ctx context.Context, LoadBalancerID core.UUID, params PartialUpdateLoadBalancerParams, body LoadBalancerPartialUpdateSchema) (*LoadBalancerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateLoadBalancerWithResponse(ctx, LoadBalancerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteLoadBalancer Delete Load Balancer
//
// DELETE /v2/load-balancing/loadbalancers/{load_balancer_id}/
func (c *Client) DeleteLoadBalancer(ctx context.Context, LoadBalancerID core.UUID, params DeleteLoadBalancerParams) error {
	genParams := params
	resp, err := c.gen.DeleteLoadBalancerWithResponse(ctx, LoadBalancerID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ConfigurePublicIpLoadBalancer Configure Public Ip Load Balancer
//
// PUT /v2/load-balancing/loadbalancers/{load_balancer_id}/public-ip/
func (c *Client) ConfigurePublicIpLoadBalancer(ctx context.Context, LoadBalancerID core.UUID, params ConfigurePublicIpLoadBalancerParams, body LoadBalancerPublicIPSchema) error {
	genParams := params
	resp, err := c.gen.ConfigurePublicIpLoadBalancerWithResponse(ctx, LoadBalancerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// GetLoadBalancerMetricsSchema Get Load Balancer Metrics Schema
//
// GET /v2/load-balancing/loadbalancers/metrics-schema/
func (c *Client) GetLoadBalancerMetricsSchema(ctx context.Context) (*MetricSchema, error) {
	resp, err := c.gen.GetLoadBalancerMetricsSchemaWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetLoadBalancerMetrics Get Load Balancer Metrics
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/metrics/
func (c *Client) GetLoadBalancerMetrics(ctx context.Context, LoadBalancerID core.UUID, params GetLoadBalancerMetricsParams) (*PagedMetricResultSchema, error) {
	genParams := params
	resp, err := c.gen.GetLoadBalancerMetricsWithResponse(ctx, LoadBalancerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// EstimateLoadBalancerCost Estimate Load Balancer Cost
//
// POST /v2/load-balancing/loadbalancers/estimate-cost/
func (c *Client) EstimateLoadBalancerCost(ctx context.Context, params EstimateLoadBalancerCostParams, body LoadBalancerEstimateCostSchema) (*EstimatedPaygCostSchema, error) {
	genParams := params
	resp, err := c.gen.EstimateLoadBalancerCostWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListListeners List Listeners
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/
func (c *Client) ListListeners(ctx context.Context, LoadBalancerID core.UUID, params ListListenersParams) (*PagedListenerSchema, error) {
	genParams := params
	resp, err := c.gen.ListListenersWithResponse(ctx, LoadBalancerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateListener Create Listener
//
// POST /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/
func (c *Client) CreateListener(ctx context.Context, LoadBalancerID core.UUID, params CreateListenerParams, body ListenerCreateSchema) (*ListenerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.CreateListenerWithResponse(ctx, LoadBalancerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetListener Get Listener
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/{listener_id}/
func (c *Client) GetListener(ctx context.Context, LoadBalancerID core.UUID, ListenerID core.UUID, params GetListenerParams) (*ListenerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetListenerWithResponse(ctx, LoadBalancerID, ListenerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateListener Update Listener
//
// PUT /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/{listener_id}/
func (c *Client) UpdateListener(ctx context.Context, LoadBalancerID core.UUID, ListenerID core.UUID, params UpdateListenerParams, body ListenerUpdateSchema) (*ListenerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateListenerWithResponse(ctx, LoadBalancerID, ListenerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateListener Partial Update Listener
//
// PATCH /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/{listener_id}/
func (c *Client) PartialUpdateListener(ctx context.Context, LoadBalancerID core.UUID, ListenerID core.UUID, params PartialUpdateListenerParams, body ListenerPartialUpdateSchema) (*ListenerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateListenerWithResponse(ctx, LoadBalancerID, ListenerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteListener Delete Listener
//
// DELETE /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/{listener_id}/
func (c *Client) DeleteListener(ctx context.Context, LoadBalancerID core.UUID, ListenerID core.UUID, params DeleteListenerParams) error {
	genParams := params
	resp, err := c.gen.DeleteListenerWithResponse(ctx, LoadBalancerID, ListenerID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// GetListenerMetricsSchema Get Listener Metrics Schema
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/metrics-schema/
func (c *Client) GetListenerMetricsSchema(ctx context.Context, LoadBalancerID core.UUID) (*MetricSchema, error) {
	resp, err := c.gen.GetListenerMetricsSchemaWithResponse(ctx, LoadBalancerID)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetListenerMetrics Get Listener Metrics
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/listeners/{listener_id}/metrics/
func (c *Client) GetListenerMetrics(ctx context.Context, LoadBalancerID core.UUID, ListenerID core.UUID, params GetListenerMetricsParams) (*PagedMetricResultSchema, error) {
	genParams := params
	resp, err := c.gen.GetListenerMetricsWithResponse(ctx, LoadBalancerID, ListenerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListListenerAuthUsers List Listener Auth Users
//
// GET /v2/load-balancing/listeners/{listener_id}/auth-users/
func (c *Client) ListListenerAuthUsers(ctx context.Context, ListenerID core.UUID, params ListListenerAuthUsersParams) (*PagedListenerAuthUserSchema, error) {
	genParams := params
	resp, err := c.gen.ListListenerAuthUsersWithResponse(ctx, ListenerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateListenerAuthUser Create Listener Auth User
//
// POST /v2/load-balancing/listeners/{listener_id}/auth-users/
func (c *Client) CreateListenerAuthUser(ctx context.Context, ListenerID core.UUID, params CreateListenerAuthUserParams, body ListenerAuthUserCreateSchema) (*ListenerAuthUserSchema, error) {
	genParams := params
	resp, err := c.gen.CreateListenerAuthUserWithResponse(ctx, ListenerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// ChangePasswordListenerAuthUser Change Password Listener Auth User
//
// POST /v2/load-balancing/listeners/{listener_id}/auth-users/{auth_user_id}/change-password/
func (c *Client) ChangePasswordListenerAuthUser(ctx context.Context, ListenerID core.UUID, AuthUserID core.UUID, params ChangePasswordListenerAuthUserParams, body ListenerAuthUserChangePasswordSchema) (*ListenerAuthUserSchema, error) {
	genParams := params
	resp, err := c.gen.ChangePasswordListenerAuthUserWithResponse(ctx, ListenerID, AuthUserID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteListenerAuthUser Delete Listener Auth User
//
// DELETE /v2/load-balancing/listeners/{listener_id}/auth-users/{auth_user_id}/
func (c *Client) DeleteListenerAuthUser(ctx context.Context, ListenerID core.UUID, AuthUserID core.UUID, params DeleteListenerAuthUserParams) error {
	genParams := params
	resp, err := c.gen.DeleteListenerAuthUserWithResponse(ctx, ListenerID, AuthUserID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListListenerRateLimits List Listener Rate Limits
//
// GET /v2/load-balancing/listeners/{listener_id}/rate-limits/
func (c *Client) ListListenerRateLimits(ctx context.Context, ListenerID core.UUID, params ListListenerRateLimitsParams) (*PagedListenerRateLimitSchema, error) {
	genParams := params
	resp, err := c.gen.ListListenerRateLimitsWithResponse(ctx, ListenerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateListenerRateLimit Create Listener Rate Limit
//
// POST /v2/load-balancing/listeners/{listener_id}/rate-limits/
func (c *Client) CreateListenerRateLimit(ctx context.Context, ListenerID core.UUID, params CreateListenerRateLimitParams, body ListenerRateLimitCreateSchema) (*ListenerRateLimitSchema, error) {
	genParams := params
	resp, err := c.gen.CreateListenerRateLimitWithResponse(ctx, ListenerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// PartialUpdateListenerRateLimit Partial Update Listener Rate Limit
//
// PATCH /v2/load-balancing/listeners/{listener_id}/rate-limits/{rate_limit_id}/
func (c *Client) PartialUpdateListenerRateLimit(ctx context.Context, ListenerID core.UUID, RateLimitID core.UUID, params PartialUpdateListenerRateLimitParams, body ListenerRateLimitPartialUpdateSchema) (*ListenerRateLimitSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateListenerRateLimitWithResponse(ctx, ListenerID, RateLimitID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteListenerRateLimit Delete Listener Rate Limit
//
// DELETE /v2/load-balancing/listeners/{listener_id}/rate-limits/{rate_limit_id}/
func (c *Client) DeleteListenerRateLimit(ctx context.Context, ListenerID core.UUID, RateLimitID core.UUID, params DeleteListenerRateLimitParams) error {
	genParams := params
	resp, err := c.gen.DeleteListenerRateLimitWithResponse(ctx, ListenerID, RateLimitID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListServerGroups List Server Groups
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/
func (c *Client) ListServerGroups(ctx context.Context, LoadBalancerID core.UUID, params ListServerGroupsParams) (*PagedServerGroupSchema, error) {
	genParams := params
	resp, err := c.gen.ListServerGroupsWithResponse(ctx, LoadBalancerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateServerGroup Create Server Group
//
// POST /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/
func (c *Client) CreateServerGroup(ctx context.Context, LoadBalancerID core.UUID, params CreateServerGroupParams, body ServerGroupCreateSchema) (*ServerGroupDetailSchema, error) {
	genParams := params
	resp, err := c.gen.CreateServerGroupWithResponse(ctx, LoadBalancerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetServerGroup Get Server Group
//
// GET /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/{server_group_id}/
func (c *Client) GetServerGroup(ctx context.Context, LoadBalancerID core.UUID, ServerGroupID core.UUID, params GetServerGroupParams) (*ServerGroupDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetServerGroupWithResponse(ctx, LoadBalancerID, ServerGroupID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateServerGroup Update Server Group
//
// PUT /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/{server_group_id}/
func (c *Client) UpdateServerGroup(ctx context.Context, LoadBalancerID core.UUID, ServerGroupID core.UUID, params UpdateServerGroupParams, body ServerGroupUpdateSchema) (*ServerGroupDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateServerGroupWithResponse(ctx, LoadBalancerID, ServerGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateServerGroup Partial Update Server Group
//
// PATCH /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/{server_group_id}/
func (c *Client) PartialUpdateServerGroup(ctx context.Context, LoadBalancerID core.UUID, ServerGroupID core.UUID, params PartialUpdateServerGroupParams, body ServerGroupPartialUpdateSchema) (*ServerGroupDetailSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateServerGroupWithResponse(ctx, LoadBalancerID, ServerGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteServerGroup Delete Server Group
//
// DELETE /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/{server_group_id}/
func (c *Client) DeleteServerGroup(ctx context.Context, LoadBalancerID core.UUID, ServerGroupID core.UUID, params DeleteServerGroupParams) error {
	genParams := params
	resp, err := c.gen.DeleteServerGroupWithResponse(ctx, LoadBalancerID, ServerGroupID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// BatchUpdateMemberServerGroup Batch Update Member Server Group
//
// PUT /v2/load-balancing/loadbalancers/{load_balancer_id}/server-groups/{server_group_id}/members/
func (c *Client) BatchUpdateMemberServerGroup(ctx context.Context, LoadBalancerID core.UUID, ServerGroupID core.UUID, params BatchUpdateMemberServerGroupParams, body ServerGroupBatchUpdateMemberSchema) error {
	genParams := params
	resp, err := c.gen.BatchUpdateMemberServerGroupWithResponse(ctx, LoadBalancerID, ServerGroupID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 200)
}

// ListServerGroupMembers List Server Group Members
//
// GET /v2/load-balancing/server-groups/{server_group_id}/members/
func (c *Client) ListServerGroupMembers(ctx context.Context, ServerGroupID core.UUID, params ListServerGroupMembersParams) (*PagedServerGroupMemberSchema, error) {
	genParams := params
	resp, err := c.gen.ListServerGroupMembersWithResponse(ctx, ServerGroupID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateServerGroupMember Create Server Group Member
//
// POST /v2/load-balancing/server-groups/{server_group_id}/members/
func (c *Client) CreateServerGroupMember(ctx context.Context, ServerGroupID core.UUID, params CreateServerGroupMemberParams, body ServerGroupMemberCreateSchema) (*ServerGroupMemberSchema, error) {
	genParams := params
	resp, err := c.gen.CreateServerGroupMemberWithResponse(ctx, ServerGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetServerGroupMember Get Server Group Member
//
// GET /v2/load-balancing/server-groups/{server_group_id}/members/{member_id}/
func (c *Client) GetServerGroupMember(ctx context.Context, ServerGroupID core.UUID, MemberID core.UUID, params GetServerGroupMemberParams) (*ServerGroupMemberSchema, error) {
	genParams := params
	resp, err := c.gen.GetServerGroupMemberWithResponse(ctx, ServerGroupID, MemberID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateServerGroupMember Update Server Group Member
//
// PUT /v2/load-balancing/server-groups/{server_group_id}/members/{member_id}/
func (c *Client) UpdateServerGroupMember(ctx context.Context, ServerGroupID core.UUID, MemberID core.UUID, params UpdateServerGroupMemberParams, body ServerGroupMemberUpdateSchema) (*ServerGroupMemberSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateServerGroupMemberWithResponse(ctx, ServerGroupID, MemberID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateServerGroupMember Partial Update Server Group Member
//
// PATCH /v2/load-balancing/server-groups/{server_group_id}/members/{member_id}/
func (c *Client) PartialUpdateServerGroupMember(ctx context.Context, ServerGroupID core.UUID, MemberID core.UUID, params PartialUpdateServerGroupMemberParams, body ServerGroupMemberPartialUpdateSchema) (*ServerGroupMemberSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateServerGroupMemberWithResponse(ctx, ServerGroupID, MemberID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteServerGroupMember Delete Server Group Member
//
// DELETE /v2/load-balancing/server-groups/{server_group_id}/members/{member_id}/
func (c *Client) DeleteServerGroupMember(ctx context.Context, ServerGroupID core.UUID, MemberID core.UUID, params DeleteServerGroupMemberParams) error {
	genParams := params
	resp, err := c.gen.DeleteServerGroupMemberWithResponse(ctx, ServerGroupID, MemberID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListL7policies List L7Policies
//
// GET /v2/load-balancing/l7policies/
func (c *Client) ListL7policies(ctx context.Context, params ListL7policiesParams) (*PagedL7PolicySchema, error) {
	genParams := params
	resp, err := c.gen.ListL7policiesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateL7policy Create L7Policy
//
// POST /v2/load-balancing/l7policies/
func (c *Client) CreateL7policy(ctx context.Context, params CreateL7policyParams, body L7PolicyCreateSchema) (*L7PolicySchema, error) {
	genParams := params
	resp, err := c.gen.CreateL7policyWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetL7policy Get L7Policy
//
// GET /v2/load-balancing/l7policies/{l7policy_id}/
func (c *Client) GetL7policy(ctx context.Context, L7policyID core.UUID, params GetL7policyParams) (*L7PolicyDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetL7policyWithResponse(ctx, L7policyID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateL7policy Update L7Policy
//
// PUT /v2/load-balancing/l7policies/{l7policy_id}/
func (c *Client) UpdateL7policy(ctx context.Context, L7policyID core.UUID, params UpdateL7policyParams, body L7PolicyUpdateSchema) (*L7PolicySchema, error) {
	genParams := params
	resp, err := c.gen.UpdateL7policyWithResponse(ctx, L7policyID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateL7policy Partial Update L7Policy
//
// PATCH /v2/load-balancing/l7policies/{l7policy_id}/
func (c *Client) PartialUpdateL7policy(ctx context.Context, L7policyID core.UUID, params PartialUpdateL7policyParams, body L7PolicyPartialUpdateSchema) (*L7PolicySchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateL7policyWithResponse(ctx, L7policyID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteL7policy Delete L7Policy
//
// DELETE /v2/load-balancing/l7policies/{l7policy_id}/
func (c *Client) DeleteL7policy(ctx context.Context, L7policyID core.UUID, params DeleteL7policyParams) error {
	genParams := params
	resp, err := c.gen.DeleteL7policyWithResponse(ctx, L7policyID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListL7rule List L7Rule
//
// GET /v2/load-balancing/l7policies/{l7policy_id}/l7rules/
func (c *Client) ListL7rule(ctx context.Context, L7policyID core.UUID, params ListL7ruleParams) (*PagedL7RuleSchema, error) {
	genParams := params
	resp, err := c.gen.ListL7ruleWithResponse(ctx, L7policyID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateL7rule Create L7Rule
//
// POST /v2/load-balancing/l7policies/{l7policy_id}/l7rules/
func (c *Client) CreateL7rule(ctx context.Context, L7policyID core.UUID, params CreateL7ruleParams, body L7RuleCreateSchema) (*L7RuleSchema, error) {
	genParams := params
	resp, err := c.gen.CreateL7ruleWithResponse(ctx, L7policyID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetL7rule Get L7Rule
//
// GET /v2/load-balancing/l7policies/{l7policy_id}/l7rules/{l7rule_id}/
func (c *Client) GetL7rule(ctx context.Context, L7policyID core.UUID, L7ruleID core.UUID, params GetL7ruleParams) (*L7RuleSchema, error) {
	genParams := params
	resp, err := c.gen.GetL7ruleWithResponse(ctx, L7policyID, L7ruleID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateL7rule Update L7Rule
//
// PUT /v2/load-balancing/l7policies/{l7policy_id}/l7rules/{l7rule_id}/
func (c *Client) UpdateL7rule(ctx context.Context, L7policyID core.UUID, L7ruleID core.UUID, params UpdateL7ruleParams, body L7RuleUpdateSchema) (*L7RuleSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateL7ruleWithResponse(ctx, L7policyID, L7ruleID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateL7rule Partial Update L7Rule
//
// PATCH /v2/load-balancing/l7policies/{l7policy_id}/l7rules/{l7rule_id}/
func (c *Client) PartialUpdateL7rule(ctx context.Context, L7policyID core.UUID, L7ruleID core.UUID, params PartialUpdateL7ruleParams, body L7RulePartialUpdateSchema) (*L7RuleSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateL7ruleWithResponse(ctx, L7policyID, L7ruleID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteL7rule Delete L7Rule
//
// DELETE /v2/load-balancing/l7policies/{l7policy_id}/l7rules/{l7rule_id}/
func (c *Client) DeleteL7rule(ctx context.Context, L7policyID core.UUID, L7ruleID core.UUID, params DeleteL7ruleParams) error {
	genParams := params
	resp, err := c.gen.DeleteL7ruleWithResponse(ctx, L7policyID, L7ruleID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListLoadBalancersIter returns an iterator over all LoadBalancerSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListLoadBalancersIter(ctx context.Context, params ListLoadBalancersParams) iter.Seq2[*LoadBalancerSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[LoadBalancerSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListLoadBalancers(ctx, p)
		if err != nil {
			return core.Page[LoadBalancerSchema]{}, err
		}
		return core.Page[LoadBalancerSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListListenersIter returns an iterator over all ListenerSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListListenersIter(ctx context.Context, LoadBalancerID core.UUID, params ListListenersParams) iter.Seq2[*ListenerSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ListenerSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListListeners(ctx, LoadBalancerID, p)
		if err != nil {
			return core.Page[ListenerSchema]{}, err
		}
		return core.Page[ListenerSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListListenerAuthUsersIter returns an iterator over all ListenerAuthUserSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListListenerAuthUsersIter(ctx context.Context, ListenerID core.UUID, params ListListenerAuthUsersParams) iter.Seq2[*ListenerAuthUserSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ListenerAuthUserSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListListenerAuthUsers(ctx, ListenerID, p)
		if err != nil {
			return core.Page[ListenerAuthUserSchema]{}, err
		}
		return core.Page[ListenerAuthUserSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListListenerRateLimitsIter returns an iterator over all ListenerRateLimitSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListListenerRateLimitsIter(ctx context.Context, ListenerID core.UUID, params ListListenerRateLimitsParams) iter.Seq2[*ListenerRateLimitSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ListenerRateLimitSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListListenerRateLimits(ctx, ListenerID, p)
		if err != nil {
			return core.Page[ListenerRateLimitSchema]{}, err
		}
		return core.Page[ListenerRateLimitSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListServerGroupsIter returns an iterator over all ServerGroupSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListServerGroupsIter(ctx context.Context, LoadBalancerID core.UUID, params ListServerGroupsParams) iter.Seq2[*ServerGroupSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ServerGroupSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListServerGroups(ctx, LoadBalancerID, p)
		if err != nil {
			return core.Page[ServerGroupSchema]{}, err
		}
		return core.Page[ServerGroupSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListServerGroupMembersIter returns an iterator over all ServerGroupMemberSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListServerGroupMembersIter(ctx context.Context, ServerGroupID core.UUID, params ListServerGroupMembersParams) iter.Seq2[*ServerGroupMemberSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ServerGroupMemberSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListServerGroupMembers(ctx, ServerGroupID, p)
		if err != nil {
			return core.Page[ServerGroupMemberSchema]{}, err
		}
		return core.Page[ServerGroupMemberSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListL7policiesIter returns an iterator over all L7PolicySchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListL7policiesIter(ctx context.Context, params ListL7policiesParams) iter.Seq2[*L7PolicySchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[L7PolicySchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListL7policies(ctx, p)
		if err != nil {
			return core.Page[L7PolicySchema]{}, err
		}
		return core.Page[L7PolicySchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListL7ruleIter returns an iterator over all L7RuleSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListL7ruleIter(ctx context.Context, L7policyID core.UUID, params ListL7ruleParams) iter.Seq2[*L7RuleSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[L7RuleSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListL7rule(ctx, L7policyID, p)
		if err != nil {
			return core.Page[L7RuleSchema]{}, err
		}
		return core.Page[L7RuleSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}
