// Code generated by "go generate"; DO NOT EDIT.

package blockstorage

import "github.com/viettelcloud-oss/sdks/go/core"

// Sentinel errors re-exported from core for convenience.
// Use with errors.Is(err, blockstorage.ErrNotFound) etc.
var (
	ErrNotFound     = core.ErrNotFound
	ErrUnauthorized = core.ErrUnauthorized
	ErrConflict     = core.ErrConflict
	ErrValidation   = core.ErrValidation
	ErrRateLimited  = core.ErrRateLimited
	ErrInternal     = core.ErrInternal
)

// APIError is an alias for core.APIError — the structured error type
// returned by all facade methods on HTTP 4xx/5xx responses.
type APIError = core.APIError

// ErrorDetail is an alias for core.ErrorDetail — a single field-level error.
type ErrorDetail = core.ErrorDetail

// ResponseError reports an unexpected status or malformed success payload.
type ResponseError = core.ResponseError
