// Code generated by "go generate"; DO NOT EDIT.

package blockstorage

import (
	"context"
	"iter"

	"github.com/viettelcloud-oss/sdks/go/core"
)

// ListVolume List Volume
//
// GET /v2/block-storage/volumes/
func (c *Client) ListVolume(ctx context.Context, params ListVolumeParams) (*PagedVolumeSchema, error) {
	genParams := params
	resp, err := c.gen.ListVolumeWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateVolume Create Volume
//
// POST /v2/block-storage/volumes/
func (c *Client) CreateVolume(ctx context.Context, params CreateVolumeParams, body VolumeCreateSchema) (*VolumeDetailSchema, error) {
	genParams := params
	resp, err := c.gen.CreateVolumeWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetVolume Get Volume
//
// GET /v2/block-storage/volumes/{volume_id}/
func (c *Client) GetVolume(ctx context.Context, VolumeID core.UUID, params GetVolumeParams) (*VolumeDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetVolumeWithResponse(ctx, VolumeID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateVolume Update Volume
//
// PATCH /v2/block-storage/volumes/{volume_id}/
func (c *Client) UpdateVolume(ctx context.Context, VolumeID core.UUID, params UpdateVolumeParams, body VolumePartialUpdateSchema) (*VolumeDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateVolumeWithResponse(ctx, VolumeID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteVolume Delete Volume
//
// DELETE /v2/block-storage/volumes/{volume_id}/
func (c *Client) DeleteVolume(ctx context.Context, VolumeID core.UUID, params DeleteVolumeParams) error {
	genParams := params
	resp, err := c.gen.DeleteVolumeWithResponse(ctx, VolumeID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ConfigureBackupPolicy Configure Backup Policy
//
// PUT /v2/block-storage/volumes/{volume_id}/backup-policy/
func (c *Client) ConfigureBackupPolicy(ctx context.Context, VolumeID core.UUID, params ConfigureBackupPolicyParams, body VolumeConfigureBackupPolicySchema) error {
	genParams := params
	resp, err := c.gen.ConfigureBackupPolicyWithResponse(ctx, VolumeID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// RetypeVolume Retype Volume
//
// POST /v2/block-storage/volumes/{volume_id}/retype/
func (c *Client) RetypeVolume(ctx context.Context, VolumeID core.UUID, params RetypeVolumeParams, body VolumeRetypeSchema) error {
	genParams := params
	resp, err := c.gen.RetypeVolumeWithResponse(ctx, VolumeID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ExtendVolume Extend Volume
//
// POST /v2/block-storage/volumes/{volume_id}/extend/
func (c *Client) ExtendVolume(ctx context.Context, VolumeID core.UUID, params ExtendVolumeParams, body VolumeExtendSchema) error {
	genParams := params
	resp, err := c.gen.ExtendVolumeWithResponse(ctx, VolumeID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// SetVolumeSnapshotPolicy Set Volume Snapshot Policy
//
// PUT /v2/block-storage/volumes/{volume_id}/snapshot-policy/
func (c *Client) SetVolumeSnapshotPolicy(ctx context.Context, VolumeID core.UUID, params SetVolumeSnapshotPolicyParams, body VolumeSnapshotPolicyUpdateSchema) error {
	genParams := params
	resp, err := c.gen.SetVolumeSnapshotPolicyWithResponse(ctx, VolumeID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListVolumeBackups List Volume Backups
//
// GET /v2/block-storage/volume-backups/
func (c *Client) ListVolumeBackups(ctx context.Context, params ListVolumeBackupsParams) (*PagedVolumeBackupSchema, error) {
	genParams := params
	resp, err := c.gen.ListVolumeBackupsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateVolumeBackup Create Volume Backup
//
// POST /v2/block-storage/volume-backups/
func (c *Client) CreateVolumeBackup(ctx context.Context, params CreateVolumeBackupParams, body VolumeBackupCreateSchema) (*VolumeBackupSchema, error) {
	genParams := params
	resp, err := c.gen.CreateVolumeBackupWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetVolumeBackup Get Volume Backup
//
// GET /v2/block-storage/volume-backups/{volume_backup_id}/
func (c *Client) GetVolumeBackup(ctx context.Context, VolumeBackupID core.UUID, params GetVolumeBackupParams) (*VolumeBackupSchema, error) {
	genParams := params
	resp, err := c.gen.GetVolumeBackupWithResponse(ctx, VolumeBackupID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateVolumeBackup Update Volume Backup
//
// PUT /v2/block-storage/volume-backups/{volume_backup_id}/
func (c *Client) UpdateVolumeBackup(ctx context.Context, VolumeBackupID core.UUID, params UpdateVolumeBackupParams, body VolumeBackupUpdateSchema) (*VolumeBackupSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateVolumeBackupWithResponse(ctx, VolumeBackupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateVolumeBackup Partial Update Volume Backup
//
// PATCH /v2/block-storage/volume-backups/{volume_backup_id}/
func (c *Client) PartialUpdateVolumeBackup(ctx context.Context, VolumeBackupID core.UUID, params PartialUpdateVolumeBackupParams, body VolumeBackupPartialUpdateSchema) (*VolumeBackupSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateVolumeBackupWithResponse(ctx, VolumeBackupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteVolumeBackup Delete Volume Backup
//
// DELETE /v2/block-storage/volume-backups/{volume_backup_id}/
func (c *Client) DeleteVolumeBackup(ctx context.Context, VolumeBackupID core.UUID, params DeleteVolumeBackupParams) error {
	genParams := params
	resp, err := c.gen.DeleteVolumeBackupWithResponse(ctx, VolumeBackupID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListVolumeSnapshots List Volume Snapshots
//
// GET /v2/block-storage/volume-snapshots/
func (c *Client) ListVolumeSnapshots(ctx context.Context, params ListVolumeSnapshotsParams) (*PagedVolumeSnapshotSchema, error) {
	genParams := params
	resp, err := c.gen.ListVolumeSnapshotsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateVolumeSnapshot Create Volume Snapshot
//
// POST /v2/block-storage/volume-snapshots/
func (c *Client) CreateVolumeSnapshot(ctx context.Context, params CreateVolumeSnapshotParams, body VolumeSnapshotCreateSchema) (*VolumeSnapshotSchema, error) {
	genParams := params
	resp, err := c.gen.CreateVolumeSnapshotWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetVolumeSnapshot Get Volume Snapshot
//
// GET /v2/block-storage/volume-snapshots/{volume_snapshot_id}/
func (c *Client) GetVolumeSnapshot(ctx context.Context, VolumeSnapshotID core.UUID, params GetVolumeSnapshotParams) (*VolumeSnapshotSchema, error) {
	genParams := params
	resp, err := c.gen.GetVolumeSnapshotWithResponse(ctx, VolumeSnapshotID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateVolumeSnapshot Update Volume Snapshot
//
// PATCH /v2/block-storage/volume-snapshots/{volume_snapshot_id}/
func (c *Client) UpdateVolumeSnapshot(ctx context.Context, VolumeSnapshotID core.UUID, params UpdateVolumeSnapshotParams, body VolumeSnapshotPartialUpdateSchema) (*VolumeSnapshotSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateVolumeSnapshotWithResponse(ctx, VolumeSnapshotID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteVolumeSnapshot Delete Volume Snapshot
//
// DELETE /v2/block-storage/volume-snapshots/{volume_snapshot_id}/
func (c *Client) DeleteVolumeSnapshot(ctx context.Context, VolumeSnapshotID core.UUID, params DeleteVolumeSnapshotParams) error {
	genParams := params
	resp, err := c.gen.DeleteVolumeSnapshotWithResponse(ctx, VolumeSnapshotID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListVolumeTypes List Volume Types
//
// GET /v2/block-storage/volume-types/
func (c *Client) ListVolumeTypes(ctx context.Context, params ListVolumeTypesParams) (*PagedVolumeTypeSchema, error) {
	genParams := params
	resp, err := c.gen.ListVolumeTypesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetVolumeType Get Volume Type
//
// GET /v2/block-storage/volume-types/{volume_type_id}/
func (c *Client) GetVolumeType(ctx context.Context, VolumeTypeID core.UUID) (*VolumeTypeSchema, error) {
	resp, err := c.gen.GetVolumeTypeWithResponse(ctx, VolumeTypeID)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListVolumeIter returns an iterator over all VolumeSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListVolumeIter(ctx context.Context, params ListVolumeParams) iter.Seq2[*VolumeSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[VolumeSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListVolume(ctx, p)
		if err != nil {
			return core.Page[VolumeSchema]{}, err
		}
		return core.Page[VolumeSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListVolumeBackupsIter returns an iterator over all VolumeBackupSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListVolumeBackupsIter(ctx context.Context, params ListVolumeBackupsParams) iter.Seq2[*VolumeBackupSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[VolumeBackupSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListVolumeBackups(ctx, p)
		if err != nil {
			return core.Page[VolumeBackupSchema]{}, err
		}
		return core.Page[VolumeBackupSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListVolumeSnapshotsIter returns an iterator over all VolumeSnapshotSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListVolumeSnapshotsIter(ctx context.Context, params ListVolumeSnapshotsParams) iter.Seq2[*VolumeSnapshotSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[VolumeSnapshotSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListVolumeSnapshots(ctx, p)
		if err != nil {
			return core.Page[VolumeSnapshotSchema]{}, err
		}
		return core.Page[VolumeSnapshotSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListVolumeTypesIter returns an iterator over all VolumeTypeSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListVolumeTypesIter(ctx context.Context, params ListVolumeTypesParams) iter.Seq2[*VolumeTypeSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[VolumeTypeSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListVolumeTypes(ctx, p)
		if err != nil {
			return core.Page[VolumeTypeSchema]{}, err
		}
		return core.Page[VolumeTypeSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}
