#!/usr/bin/env python3
"""normalize.py — rewrite the OpenAPI spec so oapi-codegen emits clean Go types.

Also strips Django operationId prefixes (app[_v2]_views_verb_resource → verb_resource).

The upstream spec is generated by Pydantic, which emits several shapes that
oapi-codegen cannot turn into a decent Go type. Each one becomes an opaque
`struct { union json.RawMessage }` plus a pile of As*/From*/Merge* helpers, and
those names leak all the way into the public facade in <svc>/types.go:

    type ServerCreateSchema_Boot                    = gen.ServerCreateSchema_Boot
    type EstimatedCostComponentSchema_Quantity      = gen.EstimatedCostComponentSchema_Quantity
    type EstimatedCostComponentSchemaQuantity0      = gen.EstimatedCostComponentSchemaQuantity0

This pass rewrites those shapes into equivalent-but-nameable ones *before*
generation, so the SDK improves without waiting on changes to the Pydantic
models. Every rewrite is wire-compatible: it narrows what the schema *says*,
never what the API actually sends.

Passes
------
  const-type     `{"const": "image"}` with no `type` becomes `interface{}`.
                 Infer the type from the const value.

  scalar-union   An `anyOf` whose non-null branches are all the same primitive
                 (ipv4 string | ipv6 string) becomes an opaque union struct.
                 Collapse to that primitive, preserving nullability.
                     NestedPrivateIPSchema_IpAddress  ->  *string

  decimal        Pydantic renders `Decimal` as a `string`/`format: decimal`.
                 Point it at core.Decimal, which decodes it without losing
                 precision.
                     EstimatedCostComponentSchema.quantity  ->  core.Decimal

  hoist-unions   An inline `oneOf`/`anyOf` of `$ref`s forces a `Parent_Property`
                 name. Lift it into a named component schema and `$ref` that, so
                 the union gets one real name and is shared across every use
                 site. The name is the union's `title`, which the backend sets
                 on every union; a union without one fails the run. The
                 discriminator is carried over, so oapi-codegen still emits
                 ValueByDiscriminator().
                     ServerCreateSchema_Boot  ->  ServerBootOptions

  overrides      An untyped (`Any`) property has no inferable type. The backend
                 no longer emits any (a `dict[str, Any]` metadata field is a
                 typed object, so it is fine), making this a safety gate: an
                 untyped property fails the run unless a policy rule types it —
                 never guessed.

  uuid-type      Every `string`/`format: uuid` gets pointed at core.UUID, which
                 is an alias for github.com/google/uuid.UUID. Same type as
                 before, named from this SDK instead of from oapi-codegen's
                 runtime, which is what lets that dependency go away.
                     openapi_types.UUID  ->  core.UUID
                 This is the one pass that also walks `paths`: most uuids in
                 the spec are path and query parameters, which never get a
                 component schema of their own.

Usage
-----
    python3 normalize.py IN.json OUT.json --module-path <go module path>
    python3 normalize.py IN.json OUT.json --policy policy.json
    python3 normalize.py IN.json OUT.json --quiet
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import OrderedDict

# Container keywords whose values are themselves schemas.
_SUBSCHEMA_LISTS = ("anyOf", "oneOf", "allOf")

# Path item keys that are operations; the rest (parameters, summary, $ref) are
# not, and must not be walked as one.
_METHODS = ("get", "put", "post", "delete", "options", "head", "patch", "trace")

# Keywords that mean "this schema says something about its type". A schema with
# none of them is an untyped `Any`.
_TYPING_KEYWORDS = ("type", "const", "$ref", "enum", "properties", "items",
                    "additionalProperties", *_SUBSCHEMA_LISTS)

# Annotations preserved when a schema's type keywords are rewritten.
_ANNOTATIONS = ("title", "description", "default", "deprecated",
                "example", "examples", "readOnly", "writeOnly")

# Constraints kept when collapsing a scalar union — only where every branch
# agrees, so the result accepts at least everything the union did.
_CONSTRAINTS = ("format", "pattern", "minLength", "maxLength", "minimum",
                "maximum", "exclusiveMinimum", "exclusiveMaximum", "multipleOf")

DEFAULT_POLICY = {
    # Go type for `string`/`format: decimal` (Pydantic Decimal). Resolved
    # against --module-path; set to a plain name like "string" to skip import.
    "decimal_go_type": "core.Decimal",
    "decimal_go_import": "core",

    # Go type for `string`/`format: uuid`. core.UUID is an alias for
    # github.com/google/uuid.UUID, so this only changes which package the
    # generated code names, not the type. Set to "" to leave uuid strings
    # alone, which hands them back to oapi-codegen's own uuid type.
    "uuid_go_type": "core.UUID",
    "uuid_go_import": "core",

    # Escape hatch for a property the backend leaves untyped. Dotted path
    # (Schema.property, [] for a list item) -> replacement schema; "*.name"
    # matches property `name` at any depth; "nullable" wraps in anyOf[..., null].
    # Empty by default: the backend types its fields, so a rule here is rare.
    "overrides": {},
}


# ---------------------------------------------------------------- utilities ---
def is_null(branch: object) -> bool:
    return isinstance(branch, dict) and branch.get("type") == "null"


def split_branches(branches: list) -> tuple[list, bool]:
    """Return (non-null branches, whether a null branch was present)."""
    real = [b for b in branches if not is_null(b)]
    return real, len(real) != len(branches)


def union_key(node: dict) -> str | None:
    for key in ("oneOf", "anyOf"):
        if isinstance(node.get(key), list):
            return key
    return None


def ref_name(branch: object) -> str | None:
    if isinstance(branch, dict) and isinstance(branch.get("$ref"), str):
        return branch["$ref"].rsplit("/", 1)[-1]
    return None


def dotted(path: list[str]) -> str:
    return ".".join(path)


def leaf_property(path: list[str]) -> str | None:
    """Last real property name in a path, skipping [] and {} markers."""
    return next((p for p in reversed(path[1:]) if p not in ("[]", "{}")), None)


def walk(node: object, path: list[str], fn) -> None:
    """Depth-first walk over every subschema, calling fn(node, path).

    fn may rewrite node in place; the walk re-reads node afterwards, so a
    rewrite is visible to the recursion below it.
    """
    if not isinstance(node, dict):
        return
    fn(node, path)
    for key in _SUBSCHEMA_LISTS:
        for branch in node.get(key) or []:
            walk(branch, path, fn)
    for prop, sub in (node.get("properties") or {}).items():
        walk(sub, path + [prop], fn)
    if isinstance(node.get("items"), dict):
        walk(node["items"], path + ["[]"], fn)
    if isinstance(node.get("additionalProperties"), dict):
        walk(node["additionalProperties"], path + ["{}"], fn)


def each_schema(spec: dict, fn) -> None:
    for name, root in (spec.get("components", {}).get("schemas") or {}).items():
        walk(root, [name], fn)


def each_path_schema(spec: dict, fn) -> None:
    """Walk the schemas that live under `paths` rather than in components.

    These are the schemas that exist only at a use site — chiefly path and
    query parameters, which never get a component of their own and so are
    invisible to each_schema. Roots are named `GET /v2/servers/.region_id` so
    a log line points at a real operation.
    """
    def params(source: dict, root: str) -> None:
        for param in source.get("parameters") or []:
            if isinstance(param, dict) and isinstance(param.get("schema"), dict):
                walk(param["schema"], [root, str(param.get("name", "?"))], fn)

    def content(source: object, root: str, label: str) -> None:
        if not isinstance(source, dict):
            return
        for media, body in (source.get("content") or {}).items():
            if isinstance(body, dict) and isinstance(body.get("schema"), dict):
                walk(body["schema"], [root, f"{label}({media})"], fn)

    for url, item in (spec.get("paths") or {}).items():
        if not isinstance(item, dict):
            continue
        # Parameters declared on the path item apply to every operation on it.
        params(item, url)
        for method, op in item.items():
            if method not in _METHODS or not isinstance(op, dict):
                continue
            root = f"{method.upper()} {url}"
            params(op, root)
            content(op.get("requestBody"), root, "body")
            for status, response in (op.get("responses") or {}).items():
                content(response, root, f"response {status}")


def replace_with(node: dict, replacement: dict, nullable: bool) -> None:
    """Swap node's type keywords for replacement, keeping its annotations."""
    keep = {k: node[k] for k in _ANNOTATIONS if k in node}
    node.clear()
    node.update(keep)
    if nullable:
        node["anyOf"] = [dict(replacement), {"type": "null"}]
    else:
        node.update(replacement)


# ------------------------------------------------------------- pass: const ---
def pass_const_type(spec: dict, log: list[str]) -> None:
    count = 0

    def fix(node, path):
        nonlocal count
        if "const" not in node or "type" in node:
            return
        value = node["const"]
        # bool is checked before int: in Python, bool is a subclass of int.
        for py_type, json_type in ((bool, "boolean"), (str, "string"),
                                   (int, "integer"), (float, "number")):
            if isinstance(value, py_type):
                node["type"] = json_type
                count += 1
                return

    each_schema(spec, fix)
    log.append(f"const-type     : typed {count} const schemas")


# ------------------------------------------------------ pass: scalar unions ---
def merge_scalar_branches(real: list[dict]) -> dict | None:
    """Collapse branches sharing one primitive type into a single schema."""
    types = {b.get("type") for b in real}
    if len(types) != 1:
        return None
    kind = types.pop()
    if kind not in ("string", "integer", "number", "boolean"):
        return None
    merged = {"type": kind}
    for key in _CONSTRAINTS:
        values = [b.get(key) for b in real]
        if values[0] is not None and all(v == values[0] for v in values):
            merged[key] = values[0]
    return merged


def pass_scalar_union(spec: dict, log: list[str]) -> None:
    count = 0

    def fix(node, path):
        nonlocal count
        key = union_key(node)
        if not key:
            return
        real, nullable = split_branches(node[key])
        if len(real) < 2 or not all(isinstance(b, dict) for b in real):
            return
        merged = merge_scalar_branches(real)
        if merged is None:
            return
        replace_with(node, merged, nullable)
        count += 1

    each_schema(spec, fix)
    log.append(f"scalar-union   : collapsed {count} same-type unions")


# ------------------------------------------------------------ pass: decimal ---
def pass_decimal(spec: dict, policy: dict, module_path: str,
                 log: list[str]) -> None:
    go_type = policy.get("decimal_go_type", "core.Decimal")
    go_import = policy.get("decimal_go_import")

    # A plain type (e.g. "string") needs no annotation: the field already is a
    # `string`/`format: decimal`, so leave it for oapi-codegen to render.
    annotation: dict = {}
    if go_type not in ("string", "number", "integer"):
        annotation["x-go-type"] = go_type
        if go_import:
            if not module_path:
                raise SystemExit(
                    f"normalize: decimal_go_type {go_type!r} needs an import, "
                    f"but --module-path was not given")
            annotation["x-go-type-import"] = {
                "name": go_import,
                "path": f"{module_path.rstrip('/')}/{go_import}",
            }

    count = 0

    def fix(node, path):
        nonlocal count
        if node.get("type") != "string" or node.get("format") != "decimal":
            return
        # An explicit x-go-type is a deliberate choice and outranks this pass.
        if annotation and "x-go-type" not in node:
            node.update({k: dict(v) if isinstance(v, dict) else v
                         for k, v in annotation.items()})
        count += 1

    each_schema(spec, fix)
    log.append(f"decimal        : pointed {count} format:decimal strings "
               f"-> {go_type}")


# ------------------------------------------------------- pass: hoist unions ---
def union_shape(node: dict, key: str, members: list[str]) -> str:
    """Identity of a union: same members, keyword and discriminator."""
    return json.dumps({"m": members, "k": key, "d": node.get("discriminator")},
                      sort_keys=True)


def pass_hoist_unions(spec: dict, log: list[str]) -> list[str]:
    schemas = spec.setdefault("components", {}).setdefault("schemas", {})

    # Phase 1 — collect. Identical unions (same members, keyword, discriminator)
    # share one hoisted schema instead of a near-duplicate per use site.
    shapes: "OrderedDict[str, dict]" = OrderedDict()

    def collect(node, path):
        # A union at the root of a component schema already has a name — a
        # Pydantic RootModel, or one this pass hoisted on an earlier run.
        if len(path) < 2:
            return
        key = union_key(node)
        if not key:
            return
        real, _ = split_branches(node[key])
        if len(real) < 2:
            return
        members = [ref_name(b) for b in real]
        if not all(members):
            return
        shape = union_shape(node, key, members)
        entry = shapes.setdefault(shape, {
            "key": key, "members": members, "branches": [dict(b) for b in real],
            "discriminator": node.get("discriminator"),
            "title": node.get("title"), "paths": [],
        })
        entry["paths"].append(list(path))

    each_schema(spec, collect)

    # A hoistable union with no title has no name we can trust. Report its first
    # use site and leave it in place, so the run fails rather than guessing.
    untitled = [dotted(e["paths"][0]) for e in shapes.values() if not e["title"]]
    named = OrderedDict((s, e) for s, e in shapes.items() if e["title"])

    # Phase 2 — name. The title is the name; a numeric suffix is a backstop for
    # the spec-bug case of a title colliding with an existing schema.
    taken = set(schemas)
    names: dict[str, str] = {}
    for shape, entry in named.items():
        name = base = entry["title"]
        suffix = 2
        while name in taken:
            name, suffix = f"{base}{suffix}", suffix + 1
        taken.add(name)
        names[shape] = name

    # Phase 3 — rewrite each use site to a bare $ref, then add the hoisted
    # schemas. The $ref keeps no annotations: the concept's docs live on the
    # hoisted schema, and a $ref with siblings makes oapi-codegen wrap it in a
    # one-off type — the Parent_Property name this pass exists to remove.
    count = 0

    def rewrite(node, path):
        nonlocal count
        if len(path) < 2:  # see collect
            return
        key = union_key(node)
        if not key:
            return
        real, nullable = split_branches(node[key])
        if len(real) < 2:
            return
        members = [ref_name(b) for b in real]
        if not all(members):
            return
        name = names.get(union_shape(node, key, members))
        if name is None:
            return
        ref = {"$ref": f"#/components/schemas/{name}"}
        node.clear()
        node.update({"anyOf": [ref, {"type": "null"}]} if nullable else ref)
        count += 1

    each_schema(spec, rewrite)

    for shape, entry in named.items():
        name = names[shape]
        hoisted = {entry["key"]: entry["branches"]}
        if entry["discriminator"]:
            hoisted["discriminator"] = entry["discriminator"]
        # A real description keeps the Go doc comment off the useless
        # "X defines model for X." default.
        hoisted["description"] = (
            f"{name} is exactly one of: {', '.join(entry['members'])}. "
            f"Use the As*/From* helpers to read or set the active variant"
            + (", or ValueByDiscriminator to dispatch on the wire value."
               if entry["discriminator"] else ".")
        )
        schemas[name] = hoisted

    log.append(f"hoist-unions   : hoisted {count} inline unions into "
               f"{len(named)} named schemas")
    for shape, entry in named.items():
        log.append(f"                 {names[shape]} = "
                   f"{' | '.join(entry['members'])}")
    return untitled


# ---------------------------------------------------------- pass: overrides ---
def pass_overrides(spec: dict, policy: dict, log: list[str]) -> list[str]:
    rules = policy.get("overrides") or {}
    applied = 0
    remaining: list[str] = []

    def match(path: list[str]) -> dict | None:
        if dotted(path) in rules:
            return rules[dotted(path)]
        leaf = leaf_property(path)
        return rules.get(f"*.{leaf}") if leaf else None

    def fix(node, path):
        nonlocal applied
        # len(path) < 2 is the component schema itself; an untyped one is a
        # free-form object by design, not a missing annotation.
        if len(path) < 2 or any(k in node for k in _TYPING_KEYWORDS):
            return
        rule = match(path)
        if rule is None:
            remaining.append(dotted(path))
            return
        rule = dict(rule)
        nullable = bool(rule.pop("nullable", False))
        replace_with(node, rule, nullable)
        applied += 1

    each_schema(spec, fix)
    log.append(f"overrides      : typed {applied} untyped properties, "
               f"{len(remaining)} left as interface{{}}")
    return remaining


# --------------------------------------------------------------- pass: uuid ---
def pass_uuid_type(spec: dict, policy: dict, module_path: str,
                   log: list[str]) -> None:
    go_type = policy.get("uuid_go_type", "core.UUID")
    go_import = policy.get("uuid_go_import")
    if not go_type:
        log.append("uuid-type      : disabled by policy")
        return
    if go_import and not module_path:
        raise SystemExit(f"normalize: uuid_go_type {go_type!r} needs an import, "
                         f"but --module-path was not given")

    annotation = {"x-go-type": go_type}
    if go_import:
        annotation["x-go-type-import"] = {
            "name": go_import,
            "path": f"{module_path.rstrip('/')}/{go_import}",
        }

    count = 0

    def fix(node, path):
        nonlocal count
        if node.get("type") != "string" or node.get("format") != "uuid":
            return
        # An explicit x-go-type, whether from the spec or an override rule,
        # is a deliberate choice and outranks this pass.
        if "x-go-type" in node:
            return
        node.update({k: dict(v) if isinstance(v, dict) else v
                     for k, v in annotation.items()})
        count += 1

    each_schema(spec, fix)
    each_path_schema(spec, fix)
    log.append(f"uuid-type      : pointed {count} uuid strings -> {go_type}")


# ---------------------------------------------------------------------- cli ---
def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("src", help="input spec (raw openapi.json)")
    parser.add_argument("dst", help="normalized spec to write")
    parser.add_argument("--module-path", default="",
                        help="Go module path, used to build x-go-type imports")
    parser.add_argument("--policy", help="JSON policy file overriding DEFAULT_POLICY")
    parser.add_argument("--quiet", action="store_true",
                        help="suppress the report; errors are still printed")
    args = parser.parse_args()

    policy = dict(DEFAULT_POLICY)
    if args.policy:
        try:
            with open(args.policy) as fh:
                policy.update(json.load(fh))
        except FileNotFoundError:
            print(f"normalize: policy file not found: {args.policy}",
                  file=sys.stderr)
            return 1
        except json.JSONDecodeError as err:
            print(f"normalize: invalid policy file {args.policy}: {err}",
                  file=sys.stderr)
            return 1

    with open(args.src) as fh:
        spec = json.load(fh)

    # Strip Django operationId prefixes (app[_v2]_views_verb_resource → verb_resource).
    op_count = 0
    for path_item in (spec.get("paths") or {}).values():
        if not isinstance(path_item, dict):
            continue
        for op in path_item.values():
            if isinstance(op, dict) and "operationId" in op:
                parts = op["operationId"].split("_views_")
                if len(parts) == 2:
                    op["operationId"] = parts[1]
                    op_count += 1

    log: list[str] = []
    if op_count:
        log.append(f"operationid-strip  : stripped {op_count} Django prefixes")
    # const-type runs first: it gives const schemas a type, which the union
    # passes rely on when deciding whether branches are primitives.
    pass_const_type(spec, log)
    pass_scalar_union(spec, log)
    pass_decimal(spec, policy, args.module_path, log)
    untitled = pass_hoist_unions(spec, log)
    remaining = pass_overrides(spec, policy, log)
    # uuid-type runs last so nothing can strip the annotation afterwards: the
    # union passes rebuild the schemas they touch, and an override rule may
    # itself introduce a uuid string.
    pass_uuid_type(spec, policy, args.module_path, log)

    if not args.quiet:
        print("\nSpec normalization")
        print("==================")
        for line in log:
            print("  " + line)
        print()

    # Both failures below are the same rule: don't guess. An untyped property
    # and an untitled union each leave a Go type no one has stated, so fail
    # here rather than carry the guesswork into generation.
    if untitled:
        distinct = sorted(set(untitled))
        noun = "union" if len(distinct) == 1 else "unions"
        print(f"normalize: {len(distinct)} {noun} of $refs with no title:",
              file=sys.stderr)
        for item in distinct:
            print(f"    * {item}", file=sys.stderr)
        print("Give the union a title in Pydantic so it can be named.",
              file=sys.stderr)
        return 1

    if remaining:
        distinct = sorted(set(remaining))
        noun = "property" if len(distinct) == 1 else "properties"
        print(f"normalize: {len(distinct)} untyped {noun} with no override rule:",
              file=sys.stderr)
        for item in distinct:
            print(f"    * {item}", file=sys.stderr)
        print("Give the field a type in Pydantic, or add an override rule for "
              "it in the normalize policy.", file=sys.stderr)
        return 1

    with open(args.dst, "w") as fh:
        json.dump(spec, fh, indent=2)
        fh.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
