// Code generated by "go generate"; DO NOT EDIT.

package project

import (
	"context"
	"log/slog"
	"net/http"

	"github.com/viettelcloud-oss/sdks/go/core"
	gen "github.com/viettelcloud-oss/sdks/go/project/internal/gen"
)

// ---------------------------------------------------------------------------
// Client
// ---------------------------------------------------------------------------

// Client wraps the generated API client and exposes typed facade methods.
type Client struct {
	gen *gen.ClientWithResponses
}

// NewClient creates a new Client for the given server URL.
//
//	c, err := project.NewClient("<api-endpoint>",
//		project.WithPAT(token),
//		project.WithHTTPClient(customHTTPClient),
//		project.WithRetry(core.DefaultRetry()),
//		project.WithUserAgent("myapp/1.2.3"),
//		project.WithLogger(slog.Default()),
//	)
func NewClient(server string, opts ...Option) (*Client, error) {
	cfg := core.ResolveClientOptions(opts...)
	var genOpts []gen.ClientOption
	for _, editor := range cfg.RequestEditors {
		editor := editor
		genOpts = append(genOpts, gen.WithRequestEditorFn(func(ctx context.Context, req *http.Request) error {
			return editor(ctx, req)
		}))
	}
	genOpts = append(genOpts, gen.WithHTTPClient(cfg.HTTPClient))

	c, err := gen.NewClientWithResponses(server, genOpts...)
	if err != nil {
		return nil, err
	}
	return &Client{gen: c}, nil
}

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

// Option configures the service-independent portions of Client.
type Option = core.ClientOption

// WithPAT sets the Personal Access Token for authentication.
// It sets the Authorization: Token <token> header on every request.
func WithPAT(token string) Option {
	return core.WithPAT(token)
}

// WithHTTPClient sets a custom http.Client (for connection pooling, proxies, TLS, etc.).
func WithHTTPClient(c *http.Client) Option {
	return core.WithHTTPClient(c)
}

// WithRetry enables retries with the given config. Use core.DefaultRetry()
// for sensible defaults or core.NoRetry() to disable.
func WithRetry(cfg *core.RetryConfig) Option {
	return core.WithRetry(cfg)
}

// WithRetryAllMethods enables retries for all HTTP methods including POST.
// By default only idempotent methods (GET, PUT, DELETE) are retried.
func WithRetryAllMethods(retry bool) Option {
	return core.WithRetryAllMethods(retry)
}

// WithUserAgent sets the User-Agent header on every request.
func WithUserAgent(ua string) Option {
	return core.WithUserAgent(ua)
}

// WithLogger enables debug logging of method, path, status, duration and request ID.
func WithLogger(l *slog.Logger) Option {
	return core.WithLogger(l)
}

// WithRequestEditor adds a custom request editor that runs on every request.
func WithRequestEditor(fn core.RequestEditorFn) Option {
	return core.WithRequestEditor(fn)
}

// WithIdempotencyKey returns a context that adds Idempotency-Key to POST
// operations. Use it only where the API documents idempotency-key support.
func WithIdempotencyKey(ctx context.Context, key string) context.Context {
	return core.WithIdempotencyKey(ctx, key)
}
