// Code generated by "go generate"; DO NOT EDIT.

package project

import (
	"context"
	"iter"

	"github.com/viettelcloud-oss/sdks/go/core"
)

// ListProjects List Projects
//
// GET /v2/projects/
func (c *Client) ListProjects(ctx context.Context, params ListProjectsParams) (*PagedProjectSchema, error) {
	genParams := params
	resp, err := c.gen.ListProjectsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListAllowedActions List Allowed Actions
//
// GET /v2/projects/{project_id}/allowed-actions/
func (c *Client) ListAllowedActions(ctx context.Context, ProjectID core.UUID, params ListAllowedActionsParams) (*PagedProjectAllowedActionSchema, error) {
	genParams := params
	resp, err := c.gen.ListAllowedActionsWithResponse(ctx, ProjectID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListProjectRegions List Project Regions
//
// GET /v2/projects/{project_id}/regions/
func (c *Client) ListProjectRegions(ctx context.Context, ProjectID core.UUID, params ListProjectRegionsParams) (*PagedProjectRegionSchema, error) {
	genParams := params
	resp, err := c.gen.ListProjectRegionsWithResponse(ctx, ProjectID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListProjectZones List Project Zones
//
// GET /v2/projects/{project_id}/zones/
func (c *Client) ListProjectZones(ctx context.Context, ProjectID core.UUID, params ListProjectZonesParams) (*PagedProjectZoneSchema, error) {
	genParams := params
	resp, err := c.gen.ListProjectZonesWithResponse(ctx, ProjectID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListProjectsIter returns an iterator over all ProjectSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListProjectsIter(ctx context.Context, params ListProjectsParams) iter.Seq2[*ProjectSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ProjectSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListProjects(ctx, p)
		if err != nil {
			return core.Page[ProjectSchema]{}, err
		}
		return core.Page[ProjectSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListProjectRegionsIter returns an iterator over all ProjectRegionSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListProjectRegionsIter(ctx context.Context, ProjectID core.UUID, params ListProjectRegionsParams) iter.Seq2[*ProjectRegionSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ProjectRegionSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListProjectRegions(ctx, ProjectID, p)
		if err != nil {
			return core.Page[ProjectRegionSchema]{}, err
		}
		return core.Page[ProjectRegionSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListProjectZonesIter returns an iterator over all ProjectZoneSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListProjectZonesIter(ctx context.Context, ProjectID core.UUID, params ListProjectZonesParams) iter.Seq2[*ProjectZoneSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ProjectZoneSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListProjectZones(ctx, ProjectID, p)
		if err != nil {
			return core.Page[ProjectZoneSchema]{}, err
		}
		return core.Page[ProjectZoneSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}
