// Code generated by "go generate"; DO NOT EDIT.

package project

import gen "github.com/viettelcloud-oss/sdks/go/project/internal/gen"

type AuthenticationError = gen.AuthenticationError
type ErrorResponseSchema = gen.ErrorResponseSchema
type ErrorSchema = gen.ErrorSchema
type InternalError = gen.InternalError
type LabeledZoneNetworkScope = gen.LabeledZoneNetworkScope
type ListAllowedActionsParams = gen.ListAllowedActionsParams
type ListProjectRegionsParams = gen.ListProjectRegionsParams
type ListProjectZonesParams = gen.ListProjectZonesParams
type ListProjectsParams = gen.ListProjectsParams
type NestedDirectorySchema = gen.NestedDirectorySchema
type NestedOrganizationSchema = gen.NestedOrganizationSchema
type NestedProjectServiceSchema = gen.NestedProjectServiceSchema
type NestedRegionSchema = gen.NestedRegionSchema
type PagedProjectAllowedActionSchema = gen.PagedProjectAllowedActionSchema
type PagedProjectRegionSchema = gen.PagedProjectRegionSchema
type PagedProjectSchema = gen.PagedProjectSchema
type PagedProjectZoneSchema = gen.PagedProjectZoneSchema
type PermissionDenied = gen.PermissionDenied
type ProjectAllowedActionSchema = gen.ProjectAllowedActionSchema
type ProjectRegionSchema = gen.ProjectRegionSchema
type ProjectSchema = gen.ProjectSchema
type ProjectServiceRegionSchema = gen.ProjectServiceRegionSchema
type ProjectStatus = gen.ProjectStatus
type ProjectZoneSchema = gen.ProjectZoneSchema
type ProviderError = gen.ProviderError
type ValidationError = gen.ValidationError
type ZoneNetworkScope = gen.ZoneNetworkScope

const (
	ProjectStatusActive      = gen.ProjectStatusActive
	ProjectStatusLocked      = gen.ProjectStatusLocked
	ProjectStatusLocking     = gen.ProjectStatusLocking
	ProjectStatusUnlocking   = gen.ProjectStatusUnlocking
	ZoneNetworkScopeExtended = gen.ZoneNetworkScopeExtended
	ZoneNetworkScopeLocal    = gen.ZoneNetworkScopeLocal
)
