// Code generated by "go generate"; DO NOT EDIT.

package server

import (
	"context"
	"iter"

	"github.com/viettelcloud-oss/sdks/go/core"
)

// ListFlavors List Flavors
//
// GET /v2/server/flavors/
func (c *Client) ListFlavors(ctx context.Context, params ListFlavorsParams) (*PagedFlavorSchema, error) {
	genParams := params
	resp, err := c.gen.ListFlavorsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetFlavor Get Flavor
//
// GET /v2/server/flavors/{flavor_id}/
func (c *Client) GetFlavor(ctx context.Context, FlavorID core.UUID, params GetFlavorParams) (*FlavorDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetFlavorWithResponse(ctx, FlavorID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListServers List Servers
//
// GET /v2/server/servers/
func (c *Client) ListServers(ctx context.Context, params ListServersParams) (*PagedServerSchema, error) {
	genParams := params
	resp, err := c.gen.ListServersWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateServer Create Server
//
// POST /v2/server/servers/
func (c *Client) CreateServer(ctx context.Context, params CreateServerParams, body ServerCreateSchema) (*ServersCreatedSchema, error) {
	genParams := params
	resp, err := c.gen.CreateServerWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetServer Get Server
//
// GET /v2/server/servers/{server_id}/
func (c *Client) GetServer(ctx context.Context, ServerID core.UUID, params GetServerParams) (*ServerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.GetServerWithResponse(ctx, ServerID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// UpdateServer Update Server
//
// PUT /v2/server/servers/{server_id}/
func (c *Client) UpdateServer(ctx context.Context, ServerID core.UUID, params UpdateServerParams, body ServerUpdateSchema) (*ServerDetailSchema, error) {
	genParams := params
	resp, err := c.gen.UpdateServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateServer Partial Update Server
//
// PATCH /v2/server/servers/{server_id}/
func (c *Client) PartialUpdateServer(ctx context.Context, ServerID core.UUID, params PartialUpdateServerParams, body ServerPartialUpdateSchema) (*ServerSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteServer Delete Server
//
// DELETE /v2/server/servers/{server_id}/
func (c *Client) DeleteServer(ctx context.Context, ServerID core.UUID, params DeleteServerParams) error {
	genParams := params
	resp, err := c.gen.DeleteServerWithResponse(ctx, ServerID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ResizeServer Resize Server
//
// POST /v2/server/servers/{server_id}/resize/
func (c *Client) ResizeServer(ctx context.Context, ServerID core.UUID, params ResizeServerParams, body ServerResizeSchema) error {
	genParams := params
	resp, err := c.gen.ResizeServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// UpdateServerPassword Update Server Password
//
// PUT /v2/server/servers/{server_id}/password/
func (c *Client) UpdateServerPassword(ctx context.Context, ServerID core.UUID, params UpdateServerPasswordParams, body ServerChangePasswordSchema) error {
	genParams := params
	resp, err := c.gen.UpdateServerPasswordWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// CloneServer Clone Server
//
// POST /v2/server/servers/{server_id}/clone/
func (c *Client) CloneServer(ctx context.Context, ServerID core.UUID, params CloneServerParams, body ServerCloneSchema) (*ServersCreatedSchema, error) {
	genParams := params
	resp, err := c.gen.CloneServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// DeleteServerCascade Delete Server Cascade
//
// POST /v2/server/servers/{server_id}/delete-cascade/
func (c *Client) DeleteServerCascade(ctx context.Context, ServerID core.UUID, params DeleteServerCascadeParams, body ServerDeleteSchema) error {
	genParams := params
	resp, err := c.gen.DeleteServerCascadeWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// AttachServerEip Attach Elastic IP
//
// POST /v2/server/servers/{server_id}/attach-eip/
func (c *Client) AttachServerEip(ctx context.Context, ServerID core.UUID, params AttachServerEipParams, body ServerElasticIPAttachSchema) error {
	genParams := params
	resp, err := c.gen.AttachServerEipWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 200)
}

// DetachServerEip Detach Elastic IP
//
// POST /v2/server/servers/{server_id}/detach-eip/
func (c *Client) DetachServerEip(ctx context.Context, ServerID core.UUID, params DetachServerEipParams, body ServerElasticIPAttachSchema) error {
	genParams := params
	resp, err := c.gen.DetachServerEipWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// AttachServerSubnet Attach Subnet
//
// POST /v2/server/servers/{server_id}/attach-subnet/
func (c *Client) AttachServerSubnet(ctx context.Context, ServerID core.UUID, params AttachServerSubnetParams, body ServerAttachSubnetSchema) error {
	genParams := params
	resp, err := c.gen.AttachServerSubnetWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 200)
}

// StartServer Start Server
//
// POST /v2/server/servers/{server_id}/start/
func (c *Client) StartServer(ctx context.Context, ServerID core.UUID, params StartServerParams) error {
	genParams := params
	resp, err := c.gen.StartServerWithResponse(ctx, ServerID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// StopServer Stop Server
//
// POST /v2/server/servers/{server_id}/stop/
func (c *Client) StopServer(ctx context.Context, ServerID core.UUID, params StopServerParams) error {
	genParams := params
	resp, err := c.gen.StopServerWithResponse(ctx, ServerID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// RebootServer Reboot Server
//
// POST /v2/server/servers/{server_id}/reboot/
func (c *Client) RebootServer(ctx context.Context, ServerID core.UUID, params RebootServerParams, body ServerRebootSchema) error {
	genParams := params
	resp, err := c.gen.RebootServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// RebuildServer Rebuild Server
//
// POST /v2/server/servers/{server_id}/rebuild/
func (c *Client) RebuildServer(ctx context.Context, ServerID core.UUID, params RebuildServerParams, body ServerRebuildSchema) error {
	genParams := params
	resp, err := c.gen.RebuildServerWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// AttachPrivateIp Attach Private IP
//
// POST /v2/server/servers/{server_id}/attach-private-ip/
func (c *Client) AttachPrivateIp(ctx context.Context, ServerID core.UUID, params AttachPrivateIpParams, body ServerAttachPrivateIPSchema) error {
	genParams := params
	resp, err := c.gen.AttachPrivateIpWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// DetachPrivateIp Detach Private IP
//
// POST /v2/server/servers/{server_id}/detach-private-ip/
func (c *Client) DetachPrivateIp(ctx context.Context, ServerID core.UUID, params DetachPrivateIpParams, body ServerDetachPrivateIPSchema) error {
	genParams := params
	resp, err := c.gen.DetachPrivateIpWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// UpdateServerBandwidth Update Server Bandwidth
//
// PUT /v2/server/servers/{server_id}/bandwidth/
func (c *Client) UpdateServerBandwidth(ctx context.Context, ServerID core.UUID, params UpdateServerBandwidthParams, body ServerUpdateBandwidthSchema) error {
	genParams := params
	resp, err := c.gen.UpdateServerBandwidthWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// UpdateServerSecurityGroup Update Server Security Groups
//
// PUT /v2/server/servers/{server_id}/security-groups/
func (c *Client) UpdateServerSecurityGroup(ctx context.Context, ServerID core.UUID, params UpdateServerSecurityGroupParams, body ServerUpdateSecurityGroupSchema) error {
	genParams := params
	resp, err := c.gen.UpdateServerSecurityGroupWithResponse(ctx, ServerID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListServerTypes List Server Types
//
// GET /v2/server/server-types/
func (c *Client) ListServerTypes(ctx context.Context, params ListServerTypesParams) (*Pagedstr, error) {
	genParams := params
	resp, err := c.gen.ListServerTypesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListCustomImages List Custom Images
//
// GET /v2/server/custom-images/
func (c *Client) ListCustomImages(ctx context.Context, params ListCustomImagesParams) (*PagedCustomImageSchema, error) {
	genParams := params
	resp, err := c.gen.ListCustomImagesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateCustomImage Create Custom Image
//
// POST /v2/server/custom-images/
func (c *Client) CreateCustomImage(ctx context.Context, params CreateCustomImageParams, body CustomImageCreateSchema) (*CustomImageSchema, error) {
	genParams := params
	resp, err := c.gen.CreateCustomImageWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetCustomImage Get Custom Image
//
// GET /v2/server/custom-images/{custom_image_id}/
func (c *Client) GetCustomImage(ctx context.Context, CustomImageID core.UUID, params GetCustomImageParams) (*CustomImageSchema, error) {
	genParams := params
	resp, err := c.gen.GetCustomImageWithResponse(ctx, CustomImageID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateCustomImage Partial Update Custom Image
//
// PATCH /v2/server/custom-images/{custom_image_id}/
func (c *Client) PartialUpdateCustomImage(ctx context.Context, CustomImageID core.UUID, params PartialUpdateCustomImageParams, body CustomImagePartialUpdateSchema) (*CustomImageSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateCustomImageWithResponse(ctx, CustomImageID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteCustomImage Delete Custom Image
//
// DELETE /v2/server/custom-images/{custom_image_id}/
func (c *Client) DeleteCustomImage(ctx context.Context, CustomImageID core.UUID, params DeleteCustomImageParams) error {
	genParams := params
	resp, err := c.gen.DeleteCustomImageWithResponse(ctx, CustomImageID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ImportCustomImage Import Custom Image
//
// POST /v2/server/custom-images/import/
func (c *Client) ImportCustomImage(ctx context.Context, params ImportCustomImageParams, body CustomImageImportSchema) (*CustomImageSchema, error) {
	genParams := params
	resp, err := c.gen.ImportCustomImageWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// ExportCustomImage Export Custom Image
//
// POST /v2/server/custom-images/{custom_image_id}/export/
func (c *Client) ExportCustomImage(ctx context.Context, CustomImageID core.UUID, params ExportCustomImageParams, body CustomImageExportSchema) error {
	genParams := params
	resp, err := c.gen.ExportCustomImageWithResponse(ctx, CustomImageID, &genParams, body)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 202)
}

// ListImages List Images
//
// GET /v2/server/images/
func (c *Client) ListImages(ctx context.Context, params ListImagesParams) (*PagedImageSchema, error) {
	genParams := params
	resp, err := c.gen.ListImagesWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetImage Get Image
//
// GET /v2/server/images/{image_id}/
func (c *Client) GetImage(ctx context.Context, ImageID core.UUID, params GetImageParams) (*ImageSchema, error) {
	genParams := params
	resp, err := c.gen.GetImageWithResponse(ctx, ImageID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// ListKeyPairs List Key Pairs
//
// GET /v2/server/key-pairs/
func (c *Client) ListKeyPairs(ctx context.Context, params ListKeyPairsParams) (*PagedKeyPairSchema, error) {
	genParams := params
	resp, err := c.gen.ListKeyPairsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// CreateKeyPair Create Key Pair
//
// POST /v2/server/key-pairs/
func (c *Client) CreateKeyPair(ctx context.Context, params CreateKeyPairParams, body KeyPairCreateSchema) (*KeyPairCreatedSchema, error) {
	genParams := params
	resp, err := c.gen.CreateKeyPairWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// GetKeyPair Get Key Pair
//
// GET /v2/server/key-pairs/{key_pair_id}/
func (c *Client) GetKeyPair(ctx context.Context, KeyPairID core.UUID, params GetKeyPairParams) (*KeyPairSchema, error) {
	genParams := params
	resp, err := c.gen.GetKeyPairWithResponse(ctx, KeyPairID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdateKeyPair Partial Update Key Pair
//
// PATCH /v2/server/key-pairs/{key_pair_id}/
func (c *Client) PartialUpdateKeyPair(ctx context.Context, KeyPairID core.UUID, params PartialUpdateKeyPairParams, body KeyPairPartialUpdateSchema) (*KeyPairSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdateKeyPairWithResponse(ctx, KeyPairID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeleteKeyPair Delete Key Pair
//
// DELETE /v2/server/key-pairs/{key_pair_id}/
func (c *Client) DeleteKeyPair(ctx context.Context, KeyPairID core.UUID, params DeleteKeyPairParams) error {
	genParams := params
	resp, err := c.gen.DeleteKeyPairWithResponse(ctx, KeyPairID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// CreatePlacementGroup Create Placement Group
//
// POST /v2/server/placement-groups/
func (c *Client) CreatePlacementGroup(ctx context.Context, params CreatePlacementGroupParams, body PlacementGroupCreateSchema) (*PlacementGroupSchema, error) {
	genParams := params
	resp, err := c.gen.CreatePlacementGroupWithResponse(ctx, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON201, 201)
}

// ListPlacementGroups List Placement Groups
//
// GET /v2/server/placement-groups/
func (c *Client) ListPlacementGroups(ctx context.Context, params ListPlacementGroupsParams) (*PagedPlacementGroupSchema, error) {
	genParams := params
	resp, err := c.gen.ListPlacementGroupsWithResponse(ctx, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// GetPlacementGroup Get Placement Group
//
// GET /v2/server/placement-groups/{placement_group_id}/
func (c *Client) GetPlacementGroup(ctx context.Context, PlacementGroupID core.UUID, params GetPlacementGroupParams) (*PlacementGroupSchema, error) {
	genParams := params
	resp, err := c.gen.GetPlacementGroupWithResponse(ctx, PlacementGroupID, &genParams)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// PartialUpdatePlacementGroup Partial Update Placement Group
//
// PATCH /v2/server/placement-groups/{placement_group_id}/
func (c *Client) PartialUpdatePlacementGroup(ctx context.Context, PlacementGroupID core.UUID, params PartialUpdatePlacementGroupParams, body PlacementGroupPartialUpdateSchema) (*PlacementGroupSchema, error) {
	genParams := params
	resp, err := c.gen.PartialUpdatePlacementGroupWithResponse(ctx, PlacementGroupID, &genParams, body)
	if err != nil {
		return nil, err
	}
	return core.ParseResponse(resp.HTTPResponse, resp.Body, resp.JSON200, 200)
}

// DeletePlacementGroup Delete Placement Group
//
// DELETE /v2/server/placement-groups/{placement_group_id}/
func (c *Client) DeletePlacementGroup(ctx context.Context, PlacementGroupID core.UUID, params DeletePlacementGroupParams) error {
	genParams := params
	resp, err := c.gen.DeletePlacementGroupWithResponse(ctx, PlacementGroupID, &genParams)
	if err != nil {
		return err
	}
	return core.ParseEmptyResponse(resp.HTTPResponse, resp.Body, 204)
}

// ListFlavorsIter returns an iterator over all FlavorSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListFlavorsIter(ctx context.Context, params ListFlavorsParams) iter.Seq2[*FlavorSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[FlavorSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListFlavors(ctx, p)
		if err != nil {
			return core.Page[FlavorSchema]{}, err
		}
		return core.Page[FlavorSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListServersIter returns an iterator over all ServerSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListServersIter(ctx context.Context, params ListServersParams) iter.Seq2[*ServerSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ServerSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListServers(ctx, p)
		if err != nil {
			return core.Page[ServerSchema]{}, err
		}
		return core.Page[ServerSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListCustomImagesIter returns an iterator over all CustomImageSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListCustomImagesIter(ctx context.Context, params ListCustomImagesParams) iter.Seq2[*CustomImageSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[CustomImageSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListCustomImages(ctx, p)
		if err != nil {
			return core.Page[CustomImageSchema]{}, err
		}
		return core.Page[CustomImageSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListImagesIter returns an iterator over all ImageSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListImagesIter(ctx context.Context, params ListImagesParams) iter.Seq2[*ImageSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[ImageSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListImages(ctx, p)
		if err != nil {
			return core.Page[ImageSchema]{}, err
		}
		return core.Page[ImageSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListKeyPairsIter returns an iterator over all KeyPairSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListKeyPairsIter(ctx context.Context, params ListKeyPairsParams) iter.Seq2[*KeyPairSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[KeyPairSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListKeyPairs(ctx, p)
		if err != nil {
			return core.Page[KeyPairSchema]{}, err
		}
		return core.Page[KeyPairSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}

// ListPlacementGroupsIter returns an iterator over all PlacementGroupSchema pages.
// Automatically advances pages until all results are exhausted.
func (c *Client) ListPlacementGroupsIter(ctx context.Context, params ListPlacementGroupsParams) iter.Seq2[*PlacementGroupSchema, error] {
	return core.Paginate(ctx, func(ctx context.Context, page, size int) (core.Page[PlacementGroupSchema], error) {
		p := params
		p.PageNumber = &page
		p.PageSize = &size
		pageResult, err := c.ListPlacementGroups(ctx, p)
		if err != nil {
			return core.Page[PlacementGroupSchema]{}, err
		}
		return core.Page[PlacementGroupSchema]{Count: pageResult.Count, Results: pageResult.Results}, nil
	})
}
